Entero a, b

Inicio
    a <- 10
    Si a < 10 Entonces
        Escriba 0
    Sino Si a = 10 Entonces
        Escriba 10
    Fin Si

    a <- 10
    Si a < 10 y a = 10 Entonces
        Escriba 'b'
    Sino Si a > 10 Entonces
        Escriba 100
    Sino Si a = 10 Entonces
        Escriba 10
    Fin Si

    a <- 10
    Si a <> 10 Entonces
        Escriba 0
    Sino Si a > 10 Entonces
        Escriba 100
    Sino Si a = 10 Entonces
        Escriba 10
    Fin Si
Fin